aliyun_oss:
  access_key_id: yourAccessKeyId
  access_key_secret: yourAccessKeySecret
  base_path: yourBasePath
  bucket_name: yourBucketName
  bucket_url: yourBucketUrl
  endpoint: yourEndpoint
autocode:
  ai_path: ''
  module: ''
  root: ''
  server: ''
  server_api: ''
  server_initialize: ''
  server_model: ''
  server_request: ''
  server_router: ''
  server_service: ''
  transfer_restart: false
  web: ''
  web_api: ''
  web_form: ''
  web_table: ''
aws_s3:
  base_url: https://rust.vue.admin
  bucket: rust-vue-admin
  disable_ssl: false
  endpoint: ''
  path_prefix: rust-vue-admin
  region: ap-shanghai
  s3_force_path_style: false
  secret_id: your-secret-id
  secret_key: your-secret-key
captcha:
  img_height: 80
  img_width: 240
  key_long: 4
  open_captcha: 0
  open_captcha_timeout: 3600
cors:
  mode: strict-whitelist
  whitelist:
  - allow_credentials: true
    allow_headers: Content-Type,AccessToken,X-CSRF-Token,Authorization,Token,X-Token,X-User-Id
    allow_methods: POST,GET,PUT,DELETE,OPTIONS
    allow_origin: http://localhost:8080
    expose_headers: Content-Length,Access-Control-Allow-Origin,Access-Control-Allow-Headers,Content-Type
  - allow_credentials: true
    allow_headers: Content-Type,Authorization,Token
    allow_methods: GET,POST,PUT,DELETE
    allow_origin: http://localhost:3000
    expose_headers: Content-Length,Access-Control-Allow-Origin,Access-Control-Allow-Headers,Content-Type
email:
  from: xxx@163.com
  host: smtp.163.com
  is_ssl: true
  nickname: rust-vue-admin
  port: 465
  secret: xxx
  to: xxx@qq.com
excel:
  dir: ./resource/excel/
jwt:
  buffer_time: 1d
  expires_time: 7d
  issuer: rust-vue-admin
  signing_key: 372eb382-dead-b1d3-8071-ce6c0354deea
local:
  path: uploads/file
  store_path: uploads/file
log:
  director: log
  format: console
  level: info
  log_in_console: true
  prefix: '[rust-vue-admin]'
  retention_day: 7
  show_line: true
minio:
  access_key_id: minioadmin
  access_key_secret: minioadmin
  base_path: ''
  bucket_name: rust-vue-admin
  bucket_url: http://localhost:9000/rust-vue-admin
  endpoint: localhost:9000
  use_ssl: false
mysql:
  config: ''
  db_name: ''
  log_mode: error
  max_idle_conns: 10
  max_open_conns: 100
  password: ''
  path: ''
  port: ''
  username: ''
pgsql:
  config: ''
  db_name: ''
  log_mode: error
  max_idle_conns: 10
  max_open_conns: 100
  password: ''
  path: ''
  port: '5432'
  username: ''
redis:
  addr: ''
  cluster_addrs:
  - 127.0.0.1:7000
  - 127.0.0.1:7001
  - 127.0.0.1:7002
  db: 0
  password: ''
  use_cluster: false
sqlite:
  log_mode: error
  max_idle_conns: 5
  max_open_conns: 10
  path: ''
system:
  addr: 8888
  db_type: mysql
  env: local
  ip_limit_count: 15000
  ip_limit_time: 3600
  oss_type: local
  router_prefix: ''
  use_multipoint: false
  use_redis: true
  use_strict_auth: false
tencent_cos:
  base_url: https://rust.vue.admin
  bucket: xxxxx-10005608
  path_prefix: rust-vue-admin
  region: ap-shanghai
  secret_id: your-secret-id
  secret_key: your-secret-key
